export class Site {
      public type : string;
      public bundesland : string;
      public isPublished: boolean
      public parkraumAusserBetriebText : string;
      public parkraumAusserBetrieb_en: string;
      public parkraumBahnhofName : string;
      public parkraumBahnhofNummer : string;
      public parkraumBemerkung : string;
      public parkraumBemerkung_en : string;
      public parkraumBetreiber : string;
      public parkraumDisplayName : string;
      public parkraumEntfernung : string;
      public parkraumGeoLatitude : string;
      public parkraumGeoLongitude : string;
      public parkraumHausnummer : string;
      public parkraumId : string;
      public parkraumIsAusserBetrieb : boolean
      public parkraumIsDbBahnPark : boolean
      public parkraumIsOpenData : boolean
      public parkraumIsParktagesproduktDbFern : boolean
      public parkraumKennung : string;
      public parkraumName : string;
      public parkraumOeffnungszeiten : string;
      public parkraumOeffnungszeiten_en : string;
      public parkraumParkTypName : string;
      public parkraumParkart : string;
      public parkraumReservierung : string;
      public parkraumSlogan : string;
      public parkraumSlogan_en : string;
      public parkraumStellplaetze : string;
      public parkraumTechnik : string;
      public parkraumTechnik_en : string;
      public parkraumURL : string;
      public parkraumZufahrt : string;
      public parkraumZufahrt_en : string;
      public tarif1MonatAutomat : string;
      public tarif1MonatDauerparken : string;
      public tarif1MonatDauerparkenFesterStellplatz : string;
      public tarif1Std : string;
      public tarif1Tag : string;
      public tarif1TagRabattDB : string;
      public tarif1Woche : string;
      public tarif1WocheRabattDB : string;
      public tarif20Min : string;
      public tarif30Min : string;
      public tarifBemerkung : string;
      public tarifBemerkung_en : string;
      public tarifFreiparkzeit : string;
      public tarifFreiparkzeit_en : string;
      public tarifMonatIsDauerparken : boolean;
      public tarifMonatIsParkAndRide : boolean;
      public tarifMonatIsParkscheinautomat : boolean;
      public tarifParkdauer : string;
      public tarifParkdauer_en : string;
      public tarifRabattDBIsBahnCard : boolean;
      public tarifRabattDBIsParkAndRail : boolean;
      public tarifRabattDBIsbahncomfort : boolean;
      public tarifSondertarif : string;
      public tarifSondertarif_en : string;
      public tarifWieRabattDB : string;
      public tarifWieRabattDB_en : string;
      public tarifWoVorverkaufDB : string;
      public tarifWoVorverkaufDB_en : string;
      public zahlungKundenkarten : string;
      public zahlungMedien : string;
      public zahlungMedien_en : string;
      public zahlungMobil : string;

      public static deserialize(obj: any): Site {
            let site = new Site();

            site.type  = obj.type;
            site.bundesland = obj.bundesland;
            site.isPublished  = obj.isPublished;
            site.parkraumAusserBetriebText = obj.parkraumAusserBetriebText;
            site.parkraumAusserBetrieb_en = obj.parkraumAusserBetrieb_en;
            site.parkraumBahnhofName = obj.parkraumBahnhofName;
            site.parkraumBahnhofNummer = obj.parkraumBahnhofNummer;
            site.parkraumBemerkung = obj.parkraumBemerkung;
            site.parkraumBemerkung_en = obj.parkraumBemerkung_en;
            site.parkraumBetreiber = obj.parkraumBetreiber;
            site.parkraumDisplayName = obj.parkraumDisplayName;
            site.parkraumEntfernung = obj.parkraumEntfernung;
            site.parkraumGeoLatitude = obj.parkraumGeoLatitude;
            site.parkraumGeoLongitude = obj.parkraumGeoLongitude;
            site.parkraumHausnummer = obj.parkraumHausnummer;
            site.parkraumId = obj.parkraumId;
            site.parkraumIsAusserBetrieb  = obj.parkraumIsAusserBetrieb;
            site.parkraumIsDbBahnPark  = obj.parkraumIsDbBahnPark;
            site.parkraumIsOpenData  = obj.parkraumIsOpenData;
            site.parkraumIsParktagesproduktDbFern  = obj.parkraumIsParktagesproduktDbFern;
            site.parkraumKennung = obj.parkraumKennung;
            site.parkraumName = obj.parkraumName;
            site.parkraumOeffnungszeiten = obj.parkraumOeffnungszeiten;
            site.parkraumOeffnungszeiten_en = obj.parkraumOeffnungszeiten_en;
            site.parkraumParkTypName = obj.parkraumParkTypName;
            site.parkraumParkart = obj.parkraumParkart;
            site.parkraumReservierung = obj.parkraumReservierung;
            site.parkraumSlogan = obj.parkraumSlogan;
            site.parkraumSlogan_en = obj.parkraumSlogan_en;
            site.parkraumStellplaetze = obj.parkraumStellplaetze;
            site.parkraumTechnik = obj.parkraumTechnik;
            site.parkraumTechnik_en = obj.parkraumTechnik_en;
            site.parkraumURL = obj.parkraumURL;
            site.parkraumZufahrt = obj.parkraumZufahrt;
            site.parkraumZufahrt_en = obj.parkraumZufahrt_en;
            site.tarif1MonatAutomat = obj.tarif1MonatAutomat;
            site.tarif1MonatDauerparken = obj.tarif1MonatDauerparken;
            site.tarif1MonatDauerparkenFesterStellplatz = obj.tarif1MonatDauerparkenFesterStellplatz;
            site.tarif1Std = obj.tarif1Std;
            site.tarif1Tag = obj.tarif1Tag;
            site.tarif1TagRabattDB = obj.tarif1TagRabattDB;
            site.tarif1Woche = obj.tarif1Woche;
            site.tarif1WocheRabattDB = obj.tarif1WocheRabattDB;
            site.tarif20Min = obj.tarif20Min;
            site.tarif30Min = obj.tarif30Min;
            site.tarifBemerkung = obj.tarifBemerkung;
            site.tarifBemerkung_en = obj.tarifBemerkung_en;
            site.tarifFreiparkzeit = obj.tarifFreiparkzeit;
            site.tarifFreiparkzeit_en = obj.tarifFreiparkzeit_en;
            site.tarifMonatIsDauerparken  = obj.tarifMonatIsDauerparken;
            site.tarifMonatIsParkAndRide  = obj.tarifMonatIsParkAndRide;
            site.tarifMonatIsParkscheinautomat  = obj.tarifMonatIsParkscheinautomat;
            site.tarifParkdauer = obj.tarifParkdauer;
            site.tarifParkdauer_en = obj.tarifParkdauer_en;
            site.tarifRabattDBIsBahnCard  = obj.tarifRabattDBIsBahnCard;
            site.tarifRabattDBIsParkAndRail  = obj.tarifRabattDBIsParkAndRail;
            site.tarifRabattDBIsbahncomfort  = obj.tarifRabattDBIsbahncomfort;
            site.tarifSondertarif = obj.tarifSondertarif;
            site.tarifSondertarif_en = obj.tarifSondertarif_en;
            site.tarifWieRabattDB = obj.tarifWieRabattDB;
            site.tarifWieRabattDB_en = obj.tarifWieRabattDB_en;
            site.tarifWoVorverkaufDB = obj.tarifWoVorverkaufDB;
            site.tarifWoVorverkaufDB_en = obj.tarifWoVorverkaufDB_en;
            site.zahlungKundenkarten = obj.zahlungKundenkarten;
            site.zahlungMedien = obj.zahlungMedien;
            site.zahlungMedien_en = obj.zahlungMedien_en;
            site.zahlungMobil = obj.zahlungMobil;

            return site;
      }
}